import { StyleSheet } from 'react-native';
import { BorderRadius, Spacing, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  const isClassic = false;

  return StyleSheet.create({
    header: {
      paddingHorizontal: isClassic ? Spacing.md : Spacing.lg,
      paddingTop: isClassic ? Spacing.md : Spacing.lg,
      paddingBottom: Spacing.md,
      gap: Spacing.md,
    },
    headerMainRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: isClassic ? 'flex-start' : 'center',
      gap: Spacing.md,
    },
    headerTitleWrap: {
      flex: 1,
      minWidth: 0,
    },
    headerSubtitle: {
      marginTop: Spacing.xs,
      lineHeight: 20,
    },
    headerIconActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      flexShrink: 0,
    },
    headerUtilityRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    notificationButton: {
      width: 40,
      height: 40,
      borderRadius: isClassic ? BorderRadius.sm : BorderRadius.md,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isClassic ? theme.backgroundDefault : theme.backgroundOverlay,
      borderWidth: 1,
      borderColor: theme.border,
      position: 'relative',
    },
    createButton: {
      width: 40,
      height: 40,
      borderRadius: isClassic ? BorderRadius.sm : BorderRadius.md,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isClassic ? theme.backgroundDefault : theme.primary,
      borderWidth: 1,
      borderColor: isClassic ? theme.primary : theme.border,
    },
    myPostsButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      paddingHorizontal: Spacing.md,
      paddingVertical: 10,
      borderRadius: BorderRadius.full,
      backgroundColor: isClassic ? theme.backgroundDefault : theme.backgroundOverlay,
      borderWidth: 1,
      borderColor: theme.border,
      minHeight: 40,
    },
    myPostsButtonActive: {
      backgroundColor: theme.accent,
      borderColor: theme.accent,
    },
    badge: {
      position: 'absolute',
      top: 2,
      right: 2,
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      paddingHorizontal: 4,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.error,
    },
    categoryContainer: {
      flexDirection: 'row',
      alignItems: 'stretch',
      paddingHorizontal: isClassic ? Spacing.md : Spacing.lg,
      paddingBottom: Spacing.md,
      gap: Spacing.sm,
    },
    categoryTab: {
      flex: 1,
      minHeight: 40,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: Spacing.xs,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.full,
      backgroundColor: isClassic ? theme.backgroundDefault : theme.backgroundOverlay,
      borderWidth: 1,
      borderColor: theme.border,
    },
    categoryTabActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    listContent: {
      paddingHorizontal: isClassic ? Spacing.md : Spacing.lg,
      paddingBottom: Spacing['5xl'],
      gap: Spacing.sm,
    },
    postCard: {
      backgroundColor: isClassic ? theme.backgroundDefault : theme.backgroundOverlay,
      borderRadius: isClassic ? BorderRadius.md : BorderRadius.lg,
      borderWidth: 1,
      borderColor: theme.border,
      padding: isClassic ? Spacing.sm : Spacing.md,
      gap: Spacing.sm,
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isClassic ? 0.01 : 0.04,
      shadowRadius: isClassic ? 4 : 12,
      elevation: isClassic ? 0 : 2,
    },
    postHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: Spacing.sm,
    },
    avatar: {
      width: 34,
      height: 34,
      borderRadius: isClassic ? BorderRadius.sm : BorderRadius.md,
      backgroundColor: isClassic ? theme.primary : theme.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    postMeta: {
      flex: 1,
      gap: 2,
    },
    pinnedTag: {
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.full,
      backgroundColor: theme.primarySoft,
    },
    postActions: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    actionBtn: {
      width: 30,
      height: 30,
      borderRadius: isClassic ? BorderRadius.sm : BorderRadius.md,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isClassic ? theme.primarySoft : theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    postTitle: {
      lineHeight: 28,
    },
    postContent: {
      lineHeight: 22,
    },
    singleImage: {
      width: '100%',
      height: 210,
      borderRadius: BorderRadius.lg,
    },
    grid2: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    gridImage2: {
      flex: 1,
      height: 126,
      borderRadius: BorderRadius.md,
    },
    imageGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.xs,
    },
    gridItem: {
      width: '32%',
      aspectRatio: 1,
      position: 'relative',
    },
    gridImage: {
      width: '100%',
      height: '100%',
      borderRadius: BorderRadius.md,
    },
    moreImagesOverlay: {
      position: 'absolute',
      inset: 0,
      borderRadius: BorderRadius.md,
      backgroundColor: 'rgba(0, 0, 0, 0.48)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    postFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
      paddingTop: Spacing.xs,
    },
    statItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    categoryTag: {
      marginLeft: 'auto',
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.full,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    emptyContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: Spacing['6xl'],
    },
    emptyText: {
      marginTop: Spacing.lg,
    },
    loadingMore: {
      paddingVertical: Spacing.lg,
      alignItems: 'center',
    },
  });
};
