import { StyleSheet, Dimensions } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export const createStyles = (theme: Theme) => {
  const isClassic = false;

  return StyleSheet.create({
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: isClassic ? Spacing.lg : Spacing["2xl"],
      paddingVertical: isClassic ? Spacing.md : Spacing.lg,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    backButton: {
      width: 40,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    scrollContent: {
      flexGrow: 1,
      paddingBottom: isClassic ? Spacing.lg : Spacing["2xl"],
    },
    postContainer: {
      padding: isClassic ? Spacing.lg : Spacing["2xl"],
      borderBottomWidth: isClassic ? StyleSheet.hairlineWidth : Spacing.md,
      borderBottomColor: theme.backgroundTertiary,
    },
    postHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: Spacing.lg,
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: BorderRadius.full,
      backgroundColor: theme.primary,
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
    },
    avatarImage: {
      width: '100%',
      height: '100%',
    },
    smallAvatar: {
      width: 32,
      height: 32,
    },
    postMeta: {
      flex: 1,
      marginLeft: Spacing.sm,
    },
    postTitle: {
      marginBottom: Spacing.md,
    },
    postContent: {
      marginBottom: Spacing.lg,
    },
    contentText: {
      lineHeight: 26,
      marginBottom: Spacing.md,
    },
    singleImage: {
      width: '100%',
      height: isClassic ? 184 : 200,
      borderRadius: isClassic ? BorderRadius.sm : BorderRadius.md,
      marginTop: Spacing.md,
    },
    grid2: {
      flexDirection: 'row',
      gap: Spacing.xs,
      marginTop: Spacing.md,
    },
    gridImage2: {
      flex: 1,
      height: 120,
      borderRadius: isClassic ? BorderRadius.sm : BorderRadius.md,
    },
    imageGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.xs,
      marginTop: Spacing.md,
    },
    gridItem: {
      width: '32%',
      aspectRatio: 1,
      position: 'relative',
    },
    gridImage: {
      width: '100%',
      height: '100%',
      borderRadius: isClassic ? BorderRadius.sm : BorderRadius.md,
    },
    moreImagesOverlay: {
      position: 'absolute',
      right: 0,
      bottom: 0,
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      borderRadius: isClassic ? BorderRadius.sm : BorderRadius.md,
      justifyContent: 'center',
      alignItems: 'center',
    },
    postActions: {
      flexDirection: 'row',
      gap: Spacing.xl,
    },
    actionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    commentsSection: {
      padding: isClassic ? Spacing.lg : Spacing["2xl"],
    },
    commentsTitle: {
      marginBottom: Spacing.lg,
    },
    emptyComments: {
      paddingVertical: Spacing["3xl"],
      alignItems: 'center',
    },
    commentItem: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: Spacing.lg,
    },
    commentAvatar: {
      width: 40,
      height: 40,
      marginTop: 2,
    },
    commentBody: {
      flex: 1,
      minWidth: 0,
      marginLeft: Spacing.md,
    },
    commentSurface: {
      paddingTop: 2,
    },
    commentNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: Spacing.xs,
    },
    authorBadge: {
      paddingHorizontal: Spacing.sm,
      paddingVertical: 2,
      borderRadius: BorderRadius.full,
      backgroundColor: theme.primaryLight,
    },
    highlightedComment: {
      backgroundColor: theme.accent + '10',
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: isClassic ? BorderRadius.sm : BorderRadius.md,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.xs,
    },
    commentContent: {
      lineHeight: 28,
      marginTop: 6,
      fontSize: 18,
    },
    commentFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: Spacing.xs,
    },
    commentMetaLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
    },
    replyLikeAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minWidth: 40,
      justifyContent: 'flex-end',
    },
    repliesContainer: {
      marginTop: Spacing.sm,
      paddingLeft: 0,
    },
    threadReplyRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      minWidth: 0,
    },
    threadReplyGap: {
      marginTop: Spacing.md,
    },
    replyAvatar: {
      width: 28,
      height: 28,
      marginTop: 2,
    },
    threadReplyBody: {
      flex: 1,
      minWidth: 0,
      marginLeft: Spacing.sm,
    },
    threadReplyItem: {
      paddingTop: 2,
    },
    replyContentText: {
      lineHeight: 24,
      marginTop: 4,
    },
    richContentBlock: {
      gap: Spacing.sm,
      marginTop: 4,
    },
    highlightedReply: {
      backgroundColor: theme.accent + '12',
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: isClassic ? BorderRadius.sm : BorderRadius.md,
      paddingHorizontal: Spacing.sm,
    },
    threadReplyMetaBar: {
      display: 'none',
    },
    commentInputContainer: {
      paddingTop: Spacing.md,
      paddingHorizontal: Spacing.lg,
      paddingBottom: Spacing.sm,
      backgroundColor: theme.backgroundDefault,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.border,
    },
    collapsedComposer: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    collapsedComposerField: {
      flex: 1,
      minHeight: 40,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      borderRadius: BorderRadius.full,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: Spacing.md,
    },
    collapsedComposerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    collapsedActionButton: {
      width: 36,
      height: 36,
      borderRadius: BorderRadius.full,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
    },
    commentImagePreviewRow: {
      gap: Spacing.sm,
      paddingBottom: Spacing.sm,
      paddingRight: Spacing.xs,
    },
    commentImagePreviewItem: {
      width: 64,
      height: 64,
      borderRadius: BorderRadius.md,
      overflow: 'hidden',
      position: 'relative',
    },
    commentImagePreview: {
      width: '100%',
      height: '100%',
    },
    commentImageRemoveButton: {
      position: 'absolute',
      top: 4,
      right: 4,
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: 'rgba(0,0,0,0.62)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    replyingTo: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.sm,
      paddingHorizontal: Spacing.sm,
    },
    commentInput: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: Spacing.sm,
    },
    commentComposer: {
      flex: 1,
      backgroundColor: theme.backgroundSecondary,
      borderRadius: BorderRadius.xl,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.sm,
      paddingBottom: Spacing.xs,
    },
    input: {
      flex: 1,
      minHeight: 52,
      maxHeight: 108,
      paddingTop: Spacing.xs,
      paddingBottom: Spacing.sm,
      fontSize: 16,
      color: theme.textPrimary,
      lineHeight: 22,
    },
    commentToolsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.lg,
      paddingTop: Spacing.xs,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.borderLight,
    },
    commentToolButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    submitButton: {
      width: 42,
      height: 42,
      backgroundColor: theme.primary,
      borderRadius: BorderRadius.full,
      alignItems: 'center',
      justifyContent: 'center',
    },
    submitButtonDisabled: {
      backgroundColor: theme.backgroundTertiary,
    },
    emojiPicker: {
      marginTop: Spacing.sm,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.border,
      paddingTop: Spacing.sm,
    },
    emojiGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.xs,
    },
    emojiItem: {
      width: '10.8%',
      aspectRatio: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BorderRadius.md,
      backgroundColor: theme.backgroundSecondary,
    },
    mentionPicker: {
      marginTop: Spacing.sm,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.border,
      paddingTop: Spacing.sm,
      gap: Spacing.sm,
    },
    mentionPickerTitle: {
      paddingHorizontal: Spacing.xs,
    },
    mentionRow: {
      gap: Spacing.sm,
      paddingRight: Spacing.sm,
    },
    mentionChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.full,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.border,
    },
    mentionAvatar: {
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    actionSheetOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.32)',
      justifyContent: 'flex-end',
    },
    actionSheet: {
      backgroundColor: theme.backgroundDefault,
      borderTopLeftRadius: BorderRadius.xl,
      borderTopRightRadius: BorderRadius.xl,
      paddingTop: Spacing.sm,
      paddingHorizontal: Spacing.lg,
      paddingBottom: Spacing.xl,
    },
    actionSheetHandle: {
      width: 40,
      height: 4,
      borderRadius: BorderRadius.full,
      backgroundColor: theme.border,
      alignSelf: 'center',
      marginBottom: Spacing.md,
    },
    actionSheetHeader: {
      gap: Spacing.xs,
      paddingBottom: Spacing.md,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
      marginBottom: Spacing.sm,
    },
    actionSheetItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
      padding: Spacing.lg,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    actionSheetItemDanger: {
      borderBottomWidth: 0,
    },
    actionSheetCancel: {
      marginTop: Spacing.md,
      paddingVertical: Spacing.lg,
      alignItems: 'center',
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.lg,
    },
    imageModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.95)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    imageModalClose: {
      position: 'absolute',
      top: 50,
      right: 20,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
    },
    imageModalContent: {
      width: SCREEN_WIDTH,
      height: SCREEN_HEIGHT,
    },
    imageScrollContent: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    imageTouchable: {
      width: SCREEN_WIDTH,
      height: SCREEN_HEIGHT,
      justifyContent: 'center',
      alignItems: 'center',
    },
    fullscreenImage: {
      width: SCREEN_WIDTH,
      height: SCREEN_HEIGHT * 0.8,
    },
    imageIndicator: {
      position: 'absolute',
      top: 60,
      left: 0,
      right: 0,
      alignItems: 'center',
      zIndex: 10,
    },
  });
};
