import { StyleSheet } from 'react-native';

// 设计稿配色
export const COLORS = {
    background: 'rgb(249,247,241)',
    cardBg: 'rgb(255,255,255)',
    primary: 'rgb(166,49,49)',
    primaryLight: 'rgba(166,49,49,0.08)',
    primaryBorder: 'rgba(166,49,49,0.15)',
    textPrimary: 'rgb(44,36,32)',
    textSecondary: 'rgb(100,90,85)',
    textMuted: 'rgb(120,110,105)',
    textHint: 'rgb(150,140,130)',
    border: 'rgba(230,224,216,0.4)',
    borderDark: 'rgba(230,224,216,1)',
    tagBg: 'rgba(230,224,216,0.5)',
    tagBgDark: 'rgba(230,224,216,0.6)',
};

export const styles = StyleSheet.create({
    loadingContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyText: {
        fontSize: 14,
        color: COLORS.textHint,
    },
    header: {
        paddingTop: 56,
        paddingHorizontal: 16,
        paddingBottom: 8,
        backgroundColor: COLORS.background,
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
        marginLeft: -8,
    },
    backText: {
        fontSize: 14,
        fontWeight: '500',
        color: COLORS.textPrimary,
        marginLeft: 4,
    },
    container: {
        flex: 1,
        paddingHorizontal: 24,
    },
    titleSection: {
        marginTop: 16,
        marginBottom: 32,
        alignItems: 'center',
        position: 'relative',
    },
    watermark: {
        position: 'absolute',
        fontSize: 96,
        fontWeight: '700',
        color: COLORS.textPrimary,
        opacity: 0.03,
        textAlign: 'center',
    },
    title: {
        fontSize: 48,
        fontWeight: '700',
        color: COLORS.textPrimary,
        letterSpacing: 12,
        zIndex: 1,
    },
    tagContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 16,
        paddingHorizontal: 16,
        paddingVertical: 6,
        backgroundColor: COLORS.tagBg,
        borderRadius: 100,
    },
    tagDynasty: {
        fontSize: 14,
        fontWeight: '600',
        color: COLORS.primary,
    },
    tagDot: {
        fontSize: 14,
        color: COLORS.textSecondary,
    },
    tagEmperor: {
        fontSize: 14,
        color: COLORS.textSecondary,
    },
    infoCards: {
        flexDirection: 'row',
        gap: 16,
        marginBottom: 32,
    },
    infoCard: {
        flex: 1,
        backgroundColor: COLORS.cardBg,
        borderRadius: 16,
        padding: 16,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: COLORS.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 1,
    },
    infoLabel: {
        fontSize: 12,
        color: COLORS.textMuted,
        marginTop: 8,
        marginBottom: 4,
    },
    infoValue: {
        fontSize: 16,
        fontWeight: '700',
        color: COLORS.textPrimary,
    },
    infoValueSmall: {
        fontSize: 12,
        fontWeight: '700',
        color: COLORS.textPrimary,
        textAlign: 'center',
        lineHeight: 18,
    },
    section: {
        marginBottom: 32,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
        gap: 8,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: COLORS.textPrimary,
    },
    sectionContent: {
        fontSize: 14,
        color: COLORS.textSecondary,
        lineHeight: 24,
        textAlign: 'justify',
    },
    timeline: {
        marginTop: 4,
        paddingLeft: 8,
        borderLeftWidth: 2,
        borderLeftColor: COLORS.borderDark,
    },
    timelineItem: {
        paddingLeft: 24,
        marginBottom: 24,
        position: 'relative',
    },
    timelineDot: {
        position: 'absolute',
        left: -5,
        top: 6,
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: COLORS.primary,
        borderWidth: 2,
        borderColor: COLORS.background,
    },
    timelineTags: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 6,
        marginBottom: 8,
    },
    eraYearBadge: {
        backgroundColor: COLORS.primaryLight,
        borderWidth: 1,
        borderColor: COLORS.primaryBorder,
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 4,
    },
    eraYearText: {
        fontSize: 12,
        fontWeight: '700',
        color: COLORS.primary,
    },
    yearBadge: {
        backgroundColor: COLORS.tagBgDark,
        borderWidth: 1,
        borderColor: COLORS.borderDark,
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 4,
    },
    yearText: {
        fontSize: 12,
        fontWeight: '500',
        color: COLORS.textSecondary,
    },
    timelineDesc: {
        fontSize: 14,
        color: COLORS.textSecondary,
        lineHeight: 22,
    },
    emptyEvents: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 24,
        backgroundColor: 'rgba(230,224,216,0.3)',
        borderRadius: 12,
        borderWidth: 1,
        borderStyle: 'dashed',
        borderColor: COLORS.border,
    },
    emptyEventsText: {
        fontSize: 14,
        color: COLORS.textHint,
    },
});
