import { StyleSheet } from 'react-native';
import { BorderRadius, Spacing, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  const isClassic = false;

  return StyleSheet.create({
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: isClassic ? Spacing.md : Spacing.lg,
      paddingTop: isClassic ? Spacing.md : Spacing.lg,
      paddingBottom: Spacing['5xl'],
    },
    header: {
      marginBottom: isClassic ? Spacing.md : Spacing.lg,
    },
    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: Spacing.md,
    },
    headerText: {
      flex: 1,
    },
    headerSubtitle: {
      marginTop: Spacing.xs,
      lineHeight: 20,
    },
    seal: {
      width: isClassic ? 36 : 42,
      height: isClassic ? 36 : 42,
      borderRadius: isClassic ? BorderRadius.sm : BorderRadius.md,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isClassic ? theme.backgroundSecondary : theme.accent,
      borderWidth: 1,
      borderColor: theme.border,
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      backgroundColor: isClassic ? theme.backgroundDefault : theme.backgroundOverlay,
      borderRadius: isClassic ? BorderRadius.md : BorderRadius.lg,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.md,
      marginBottom: Spacing.lg,
    },
    searchInput: {
      flex: 1,
      fontSize: 15,
      color: theme.textPrimary,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: isClassic ? 'flex-start' : 'space-between',
      columnGap: isClassic ? Spacing.sm : 0,
      marginBottom: Spacing.sm,
    },
    categoriesWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: Spacing.sm,
      marginBottom: Spacing.lg,
    },
    categoryCard: {
      width: isClassic ? '100%' : '48.5%',
      minHeight: isClassic ? 94 : 116,
      padding: isClassic ? Spacing.sm : Spacing.md,
      borderRadius: isClassic ? BorderRadius.md : BorderRadius.lg,
      backgroundColor: isClassic ? theme.backgroundDefault : theme.backgroundOverlay,
      borderWidth: 1,
      borderColor: theme.border,
      justifyContent: 'space-between',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isClassic ? 0.01 : 0.04,
      shadowRadius: isClassic ? 4 : 12,
      elevation: isClassic ? 0 : 2,
    },
    categoryCardDisabled: {
      opacity: 0.82,
    },
    categoryTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    categoryStamp: {
      width: 30,
      height: 30,
      borderRadius: BorderRadius.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    categoryCount: {
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.full,
      backgroundColor: theme.backgroundSecondary,
    },
    categoryBody: {
      marginTop: Spacing.md,
      gap: Spacing.xs,
    },
    mapCard: {
      height: isClassic ? 156 : 184,
      borderRadius: isClassic ? BorderRadius.md : BorderRadius.lg,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: Spacing.sm,
      justifyContent: 'space-between',
      padding: isClassic ? Spacing.md : Spacing.lg,
    },
    mapCardTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    mapBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.full,
      backgroundColor: 'rgba(255,255,255,0.72)',
    },
    mapCaption: {
      padding: Spacing.md,
      borderRadius: isClassic ? BorderRadius.md : BorderRadius.lg,
      backgroundColor: 'rgba(255, 250, 241, 0.82)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.48)',
    },
    mapCaptionMeta: {
      marginTop: Spacing.xs,
    },
    listGroup: {
      gap: Spacing.sm,
      marginBottom: Spacing.lg,
    },
    listItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      padding: isClassic ? Spacing.sm : Spacing.md,
      borderRadius: isClassic ? BorderRadius.md : BorderRadius.lg,
      backgroundColor: isClassic ? theme.backgroundDefault : theme.backgroundOverlay,
      borderWidth: 1,
      borderColor: theme.border,
    },
    listStamp: {
      width: 30,
      height: 30,
      borderRadius: BorderRadius.md,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.accentSoft,
    },
    listContent: {
      flex: 1,
      gap: 2,
    },
    statsCard: {
      borderRadius: isClassic ? BorderRadius.md : BorderRadius.lg,
      borderWidth: 1,
      borderColor: theme.border,
      padding: isClassic ? Spacing.md : Spacing.lg,
      backgroundColor: isClassic ? theme.backgroundDefault : theme.backgroundOverlay,
    },
    statsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: Spacing.md,
      marginTop: Spacing.md,
    },
    statItem: {
      width: '48%',
      padding: Spacing.md,
      borderRadius: BorderRadius.md,
      backgroundColor: theme.backgroundSecondary,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
  });
};
